import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const inputFiles = [
  "src/domain/url.js",
  "src/data/listingModel.js",
  "src/data/listingExtractor.js",
  "src/domain/pricingInsights.js",
  "src/domain/settings.js",
  "src/domain/currency.js",
  "src/ui/renderInsightsPanel.js",
  "src/ui/theme.js",
  "src/content/boot.js"
];

const outputFile = path.join(rootDir, "src/contentScript.js");

function readFile(relativePath) {
  const fullPath = path.join(rootDir, relativePath);
  return fs.readFileSync(fullPath, "utf8").trimEnd();
}

const banner = [
  "/*",
  " * Grailed Plus content bundle",
  " * Generated by: npm run build",
  " */",
  ""
].join("\n");

const contents = inputFiles.map(readFile);
const output = `${banner}${contents.join("\n\n")}\n`;

fs.writeFileSync(outputFile, output, "utf8");
console.log(`Built ${path.relative(rootDir, outputFile)}`);
