import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const transpileRoot = path.join(rootDir, ".tmp", "ts-build");
const runtimeEntryTsFiles = [
  "src/background.ts",
  "src/options.ts",
  "src/popup.ts",
  "src/domain/browserStorage.ts",
  "src/domain/settings.ts",
  "src/domain/currency.ts"
];
const uiCssPath = path.join(rootDir, "src", "ui.css");
const contentCssBasePath = path.join(rootDir, "src", "contentScript.base.css");
const contentCssOutputPath = path.join(rootDir, "src", "contentScript.css");

const inputFiles = [
  "src/domain/url.js",
  "src/domain/normalize.js",
  "src/domain/browserStorage.js",
  "src/data/listingModel.js",
  "src/data/listingExtractor.js",
  "src/domain/pricingInsights.js",
  "src/domain/settings.js",
  "src/domain/currency.js",
  "src/domain/querySynthesis.js",
  "src/domain/providerFilters.js",
  "src/domain/depopProvider.js",
  "src/domain/marketProviders.js",
  "src/domain/matchScoring.js",
  "src/domain/marketCompareController.js",
  "src/ui/renderInsightsPanel.js",
  "src/ui/theme.js",
  "src/content/runtimeState.js",
  "src/content/navigationLifecycle.js",
  "src/content/darkModeLifecycle.js",
  "src/content/filterScopeLifecycle.js",
  "src/content/cardCurrencyLifecycle.js",
  "src/content/marketCompareLifecycle.js",
  "src/content/currencyLifecycle.js",
  "src/content/listingInsightsLifecycle.js",
  "src/content/unavailableLifecycle.js",
  "src/content/runLifecycle.js",
  "src/content/retryLifecycle.js",
  "src/content/listingRenderLifecycle.js",
  "src/content/listingPipelineLifecycle.js",
  "src/content/boot.js"
];

const outputFile = path.join(rootDir, "src/contentScript.js");

function readFile(relativePath) {
  const fullPath = path.join(rootDir, relativePath);
  return fs.readFileSync(fullPath, "utf8").trimEnd();
}

function ensureDirectoryFor(filePath) {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
}

function resolveSourcePath(relativeJsPath) {
  const absoluteJsPath = path.join(rootDir, relativeJsPath);
  const absoluteTsPath = absoluteJsPath.replace(/\.js$/, ".ts");

  if (fs.existsSync(absoluteTsPath)) {
    return {
      type: "ts",
      absolutePath: absoluteTsPath,
      relativeTsPath: relativeJsPath.replace(/\.js$/, ".ts")
    };
  }

  return {
    type: "js",
    absolutePath: absoluteJsPath,
    relativeTsPath: null
  };
}

function transpileTypeScript(relativeTsPath) {
  const absoluteTsPath = path.join(rootDir, relativeTsPath);
  const source = fs.readFileSync(absoluteTsPath, "utf8");
  const transpiled = ts.transpileModule(source, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2020,
      module: ts.ModuleKind.CommonJS,
      moduleResolution: ts.ModuleResolutionKind.NodeJs,
      lib: ["ES2020", "DOM"],
      strict: true,
      removeComments: false
    },
    fileName: absoluteTsPath,
    reportDiagnostics: true
  });

  if (Array.isArray(transpiled.diagnostics) && transpiled.diagnostics.length > 0) {
    const diagnostics = ts.formatDiagnosticsWithColorAndContext(transpiled.diagnostics, {
      getCanonicalFileName: (fileName) => fileName,
      getCurrentDirectory: () => rootDir,
      getNewLine: () => "\n"
    });
    throw new Error(`TypeScript transpile diagnostics for ${relativeTsPath}\n${diagnostics}`);
  }

  const outputRelativePath = relativeTsPath.replace(/\.ts$/, ".js");
  const outputAbsolutePath = path.join(transpileRoot, outputRelativePath);
  ensureDirectoryFor(outputAbsolutePath);
  fs.writeFileSync(outputAbsolutePath, transpiled.outputText.trimEnd(), "utf8");

  return outputAbsolutePath;
}

function readSourceForBundle(relativeJsPath) {
  const resolved = resolveSourcePath(relativeJsPath);
  if (resolved.type === "ts" && resolved.relativeTsPath) {
    const transpiledPath = transpileTypeScript(resolved.relativeTsPath);
    return fs.readFileSync(transpiledPath, "utf8").trimEnd();
  }

  return fs.readFileSync(resolved.absolutePath, "utf8").trimEnd();
}

function buildContentCssBundle() {
  const uiCss = fs.readFileSync(uiCssPath, "utf8").trimEnd();
  const contentCssBase = fs.readFileSync(contentCssBasePath, "utf8").trimEnd();
  const banner = [
    "/*",
    " * Grailed Plus content CSS bundle",
    " * Generated by: npm run build",
    " */",
    ""
  ].join("\n");
  const output = `${banner}${uiCss}\n\n${contentCssBase}\n`;
  fs.writeFileSync(contentCssOutputPath, output, "utf8");
}

function emitRuntimeEntry(relativeTsPath) {
  const transpiledPath = transpileTypeScript(relativeTsPath);
  const outputRelativePath = relativeTsPath.replace(/\.ts$/, ".js");
  const outputAbsolutePath = path.join(rootDir, outputRelativePath);

  ensureDirectoryFor(outputAbsolutePath);
  fs.copyFileSync(transpiledPath, outputAbsolutePath);
}

const banner = [
  "/*",
  " * Grailed Plus content bundle",
  " * Generated by: npm run build",
  " */",
  ""
].join("\n");

fs.rmSync(transpileRoot, { recursive: true, force: true });
buildContentCssBundle();

const contents = inputFiles.map(readSourceForBundle);
const output = `${banner}${contents.join("\n\n")}\n`;

fs.writeFileSync(outputFile, output, "utf8");

runtimeEntryTsFiles.forEach(emitRuntimeEntry);

console.log(`Built ${path.relative(rootDir, outputFile)}`);
