/*
 * Grailed Plus content bundle
 * Generated by: npm run build
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.GrailedPlusUrl = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  function isNumericId(value) {
    return /^\d+$/.test(String(value || "").trim());
  }

  function normalizeToPath(input) {
    if (typeof input !== "string") {
      return "";
    }

    if (input.startsWith("http://") || input.startsWith("https://")) {
      try {
        return new URL(input).pathname;
      } catch (_) {
        return input;
      }
    }

    return input;
  }

  function parseListingIdFromUrl(input) {
    if (isNumericId(input)) {
      return String(input).trim();
    }

    var source = normalizeToPath(String(input || ""));
    var match = source.match(/\/listings\/(\d+)(?:[^\d]|$)/);
    if (match && match[1]) {
      return match[1];
    }

    return null;
  }

  function isListingPath(pathname) {
    if (typeof pathname !== "string") {
      return false;
    }
    return pathname.indexOf("/listings/") !== -1;
  }

  return {
    parseListingIdFromUrl: parseListingIdFromUrl,
    isListingPath: isListingPath
  };
});

(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.GrailedPlusListingAdapter = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  function createDefaultListing(sourceStatus) {
    return {
      id: null,
      title: "",
      priceDrops: [],
      createdAt: null,
      priceUpdatedAt: null,
      seller: {
        createdAt: null
      },
      prettyPath: null,
      sold: false,
      rawListing: null,
      sourceStatus: sourceStatus || "missing_listing"
    };
  }

  function getNestedValue(input, paths, fallback) {
    var i;
    var path;
    var value;
    var cursor;
    var j;

    for (i = 0; i < paths.length; i += 1) {
      path = paths[i];
      cursor = input;

      for (j = 0; j < path.length; j += 1) {
        if (cursor == null || typeof cursor !== "object") {
          cursor = undefined;
          break;
        }
        cursor = cursor[path[j]];
      }

      value = cursor;
      if (value !== undefined && value !== null) {
        return value;
      }
    }

    return fallback;
  }

  function normalizeDate(value) {
    if (!value) {
      return null;
    }

    var date = new Date(value);
    if (Number.isNaN(date.getTime())) {
      return null;
    }

    return date.toISOString();
  }

  function normalizeString(value, fallback) {
    if (typeof value === "string") {
      return value;
    }
    if (value == null) {
      return fallback;
    }

    try {
      return String(value);
    } catch (_) {
      return fallback;
    }
  }

  function normalizeListingId(value) {
    if (typeof value === "number" && Number.isInteger(value) && value > 0) {
      return value;
    }

    if (typeof value === "string" && /^\d+$/.test(value.trim())) {
      var parsed = Number(value.trim());
      return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
    }

    return null;
  }

  function normalizePriceDrops(value) {
    if (!Array.isArray(value)) {
      return [];
    }

    return value
      .map(function (entry) {
        if (typeof entry === "object" && entry !== null) {
          return Number(entry.amount || entry.price || entry.value);
        }
        return Number(entry);
      })
      .filter(function (entry) {
        return Number.isFinite(entry) && entry > 0;
      });
  }

  function getRawListing(rawNextData) {
    return getNestedValue(
      rawNextData,
      [
        ["props", "pageProps", "listing"],
        ["pageProps", "listing"],
        ["props", "listing"],
        ["listing"]
      ],
      null
    );
  }

  function mapRawListingToModel(rawListing) {
    if (!rawListing || typeof rawListing !== "object") {
      return createDefaultListing("missing_listing");
    }

    var seller = getNestedValue(rawListing, [["seller"]], {});
    var model = createDefaultListing("ok");

    model.id = normalizeListingId(getNestedValue(rawListing, [["id"]], null));
    model.title = normalizeString(getNestedValue(rawListing, [["title"]], ""), "");
    model.priceDrops = normalizePriceDrops(
      getNestedValue(rawListing, [["priceDrops"], ["price_drops"]], [])
    );
    model.createdAt = normalizeDate(
      getNestedValue(rawListing, [["createdAt"], ["created_at"], ["trueCreatedAt"], ["true_created_at"]], null)
    );
    model.priceUpdatedAt = normalizeDate(
      getNestedValue(rawListing, [["priceUpdatedAt"], ["price_updated_at"]], null)
    );
    model.seller.createdAt = normalizeDate(
      getNestedValue(seller, [["createdAt"], ["created_at"]], null)
    );

    model.prettyPath = normalizeString(
      getNestedValue(rawListing, [["prettyPath"], ["pretty_path"]], null),
      null
    );
    model.sold = Boolean(getNestedValue(rawListing, [["sold"]], false));
    model.rawListing = rawListing;

    if (!model.id) {
      model.sourceStatus = "missing_listing_id";
    }

    return model;
  }

  function fromNextData(rawNextData) {
    var rawListing = getRawListing(rawNextData);
    return mapRawListingToModel(rawListing);
  }

  return {
    createDefaultListing: createDefaultListing,
    fromNextData: fromNextData,
    mapRawListingToModel: mapRawListingToModel
  };
});

(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.GrailedPlusExtractListing = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  var Adapter = null;
  if (typeof globalThis !== "undefined" && globalThis.GrailedPlusListingAdapter) {
    Adapter = globalThis.GrailedPlusListingAdapter;
  }
  if (!Adapter && typeof require === "function") {
    try {
      Adapter = require("./listingAdapter.js");
    } catch (_) {
      Adapter = null;
    }
  }

  function safeParseJson(text) {
    if (!text || typeof text !== "string") {
      return null;
    }

    try {
      return JSON.parse(text);
    } catch (_) {
      return null;
    }
  }

  function readNextDataFromDocument(doc) {
    if (!doc || typeof doc.getElementById !== "function") {
      return null;
    }

    var node = doc.getElementById("__NEXT_DATA__");
    if (!node || !node.textContent) {
      return null;
    }

    return safeParseJson(node.textContent);
  }

  function extractListing(rawNextData) {
    if (Adapter && typeof Adapter.fromNextData === "function") {
      return Adapter.fromNextData(rawNextData);
    }

    // Fallback defaults if the adapter module fails to load.
    return {
      id: null,
      title: "",
      priceDrops: [],
      createdAt: null,
      priceUpdatedAt: null,
      seller: {
        createdAt: null
      },
      prettyPath: null,
      sold: false,
      rawListing: null,
      sourceStatus: "adapter_unavailable"
    };
  }

  return {
    readNextDataFromDocument: readNextDataFromDocument,
    extractListing: extractListing
  };
});

(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.GrailedPlusMetrics = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  var DAY_MS = 24 * 60 * 60 * 1000;

  function computeAverageDropAmount(priceDrops) {
    if (!Array.isArray(priceDrops) || priceDrops.length < 2) {
      return null;
    }

    var deltas = [];
    var i;
    var sum = 0;

    for (i = 0; i < priceDrops.length - 1; i += 1) {
      deltas.push(Number(priceDrops[i]) - Number(priceDrops[i + 1]));
    }

    for (i = 0; i < deltas.length; i += 1) {
      if (!Number.isFinite(deltas[i])) {
        return null;
      }
      sum += deltas[i];
    }

    return sum / deltas.length;
  }

  function computeAverageDropPercent(priceDrops) {
    if (!Array.isArray(priceDrops) || priceDrops.length < 2) {
      return null;
    }

    var percents = [];
    var i;
    var current;
    var next;
    var sum = 0;

    for (i = 0; i < priceDrops.length - 1; i += 1) {
      current = Number(priceDrops[i]);
      next = Number(priceDrops[i + 1]);
      if (!Number.isFinite(current) || !Number.isFinite(next) || current <= 0) {
        return null;
      }
      percents.push(100 - (next / current) * 100);
    }

    for (i = 0; i < percents.length; i += 1) {
      sum += percents[i];
    }

    return Math.floor(sum / percents.length);
  }

  function parseDate(value) {
    if (!value) {
      return null;
    }
    var date = new Date(value);
    if (Number.isNaN(date.getTime())) {
      return null;
    }
    return date;
  }

  function computeExpectedDrop(listing, nowMs) {
    var priceDrops = Array.isArray(listing && listing.priceDrops) ? listing.priceDrops : [];
    if (priceDrops.length < 1) {
      return {
        expectedDropDays: null,
        expectedDropState: "insufficient_data"
      };
    }

    var createdAt = parseDate(listing.createdAt);
    var updatedAt = parseDate(listing.priceUpdatedAt);
    if (!createdAt || !updatedAt) {
      return {
        expectedDropDays: null,
        expectedDropState: "insufficient_data"
      };
    }

    var dropIntervalMs = (updatedAt.getTime() - createdAt.getTime()) / priceDrops.length;
    if (!Number.isFinite(dropIntervalMs) || dropIntervalMs <= 0) {
      return {
        expectedDropDays: null,
        expectedDropState: "insufficient_data"
      };
    }

    var msUntilNextDrop = dropIntervalMs - (nowMs - updatedAt.getTime());
    var expectedDropDays = Math.round(msUntilNextDrop / DAY_MS);

    if (expectedDropDays < -30) {
      return {
        expectedDropDays: expectedDropDays,
        expectedDropState: "inactive"
      };
    }

    return {
      expectedDropDays: expectedDropDays,
      expectedDropState: "scheduled"
    };
  }

  function computeMetrics(listing, nowMs) {
    var now = Number.isFinite(nowMs) ? nowMs : Date.now();
    var expected = computeExpectedDrop(listing, now);
    var priceDrops = Array.isArray(listing && listing.priceDrops) ? listing.priceDrops : [];

    return {
      avgDropAmount: computeAverageDropAmount(priceDrops),
      avgDropPercent: computeAverageDropPercent(priceDrops),
      expectedDropDays: expected.expectedDropDays,
      expectedDropState: expected.expectedDropState,
      totalDrops: priceDrops.length
    };
  }

  return {
    computeAverageDropAmount: computeAverageDropAmount,
    computeAverageDropPercent: computeAverageDropPercent,
    computeExpectedDrop: computeExpectedDrop,
    computeMetrics: computeMetrics
  };
});

(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.GrailedPlusRender = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  var PANEL_ATTR = "data-grailed-plus-panel";
  var PANEL_ATTR_VALUE = "1";

  function formatCurrency(value) {
    if (!Number.isFinite(value)) {
      return "N/A";
    }
    return "$" + Math.round(value).toLocaleString("en-US");
  }

  function formatDate(isoValue) {
    if (!isoValue) {
      return "Unknown";
    }
    var date = new Date(isoValue);
    if (Number.isNaN(date.getTime())) {
      return "Unknown";
    }
    return date.toDateString();
  }

  function createRow(doc, label, value, extraClass) {
    var row = doc.createElement("div");
    row.className = "grailed-plus__row" + (extraClass ? " " + extraClass : "");

    var labelNode = doc.createElement("span");
    labelNode.className = "grailed-plus__label";
    labelNode.textContent = label;

    var valueNode = doc.createElement("span");
    valueNode.className = "grailed-plus__value";
    valueNode.textContent = value;

    row.appendChild(labelNode);
    row.appendChild(valueNode);
    return row;
  }

  function removeExistingPanels(doc) {
    if (!doc || typeof doc.querySelectorAll !== "function") {
      return;
    }

    var existingPanels = doc.querySelectorAll("[" + PANEL_ATTR + '="' + PANEL_ATTR_VALUE + '"]');
    Array.prototype.forEach.call(existingPanels, function (panel) {
      if (panel && typeof panel.remove === "function") {
        panel.remove();
      } else if (panel && panel.parentNode) {
        panel.parentNode.removeChild(panel);
      }
    });
  }

  function findMountNode(doc) {
    if (!doc || typeof doc.querySelector !== "function") {
      return null;
    }

    var selectors = [
      '[data-testid="listing-price"]',
      '[data-testid*="price"]',
      '[class*="listing-price"]',
      '[class*="ListingPrice"]',
      '[class*="price"][class*="listing"]',
      'main h1'
    ];

    var i;
    var node;
    for (i = 0; i < selectors.length; i += 1) {
      node = doc.querySelector(selectors[i]);
      if (node) {
        return node;
      }
    }

    if (typeof doc.querySelectorAll === "function") {
      var ctaCandidates = doc.querySelectorAll("button, a");
      var cta;
      for (i = 0; i < ctaCandidates.length; i += 1) {
        cta = ctaCandidates[i];
        if (!cta || typeof cta.textContent !== "string") {
          continue;
        }
        if (/buy now|make offer|send offer/i.test(cta.textContent)) {
          if (typeof cta.closest === "function") {
            node = cta.closest("section, article, div");
            if (node) {
              return node;
            }
          }
          return cta;
        }
      }
    }

    return doc.querySelector("main") || doc.body || null;
  }

  function openMetadataInNewTab(rawListing, listing) {
    var payload = rawListing || (listing && listing.rawListing) || listing || {};
    var blob;
    var objectUrl;
    var newWindow;

    try {
      blob = new Blob([JSON.stringify(payload, null, 2)], {
        type: "application/json"
      });
      objectUrl = URL.createObjectURL(blob);
      newWindow = window.open(objectUrl, "_blank", "noopener,noreferrer");

      if (!newWindow) {
        var link = document.createElement("a");
        link.href = objectUrl;
        link.target = "_blank";
        link.rel = "noopener noreferrer";
        link.click();
      }

      setTimeout(function () {
        URL.revokeObjectURL(objectUrl);
      }, 60000);
    } catch (_) {
      // Intentionally silent. The metadata feature is non-blocking.
    }
  }

  function buildExpectedDropText(listing, metrics) {
    if (metrics.expectedDropState === "inactive") {
      return "Listing appears inactive. Last update was " + formatDate(listing.priceUpdatedAt);
    }

    if (metrics.expectedDropState === "scheduled" && Number.isFinite(metrics.expectedDropDays)) {
      return String(metrics.expectedDropDays) + " days";
    }

    return "Not enough data to estimate";
  }

  function renderPanel(options) {
    var listing = options && options.listing ? options.listing : {};
    var metrics = options && options.metrics ? options.metrics : {};
    var mountNode = options && options.mountNode ? options.mountNode : null;
    var rawListing = options && options.rawListing ? options.rawListing : null;
    var statusMessage = options && options.statusMessage ? String(options.statusMessage) : "";
    var doc = (mountNode && mountNode.ownerDocument) || document;

    if (!mountNode || !doc || typeof doc.createElement !== "function") {
      return null;
    }

    removeExistingPanels(doc);

    var panel = doc.createElement("section");
    panel.className = "grailed-plus-panel";
    panel.setAttribute(PANEL_ATTR, PANEL_ATTR_VALUE);

    var heading = doc.createElement("h2");
    heading.className = "grailed-plus-panel__title";
    heading.textContent = "Grailed Plus";
    panel.appendChild(heading);

    if (statusMessage) {
      panel.appendChild(createRow(doc, "Status", statusMessage, "grailed-plus__row--status"));
    }

    var historyText;
    if (Array.isArray(listing.priceDrops) && listing.priceDrops.length > 0) {
      historyText = listing.priceDrops
        .map(function (value) {
          return formatCurrency(Number(value));
        })
        .join(", ");
      historyText += " (total drops: " + listing.priceDrops.length + ")";
    } else {
      historyText = "No price drops on record";
    }

    panel.appendChild(createRow(doc, "Price History", historyText));

    var avgText = "N/A";
    if (Number.isFinite(metrics.avgDropPercent) && Number.isFinite(metrics.avgDropAmount)) {
      avgText = String(metrics.avgDropPercent) + "% (" + formatCurrency(metrics.avgDropAmount) + ")";
    }

    var avgClass = "";
    if (metrics.avgDropPercent === 10 && Array.isArray(listing.priceDrops) && listing.priceDrops.length > 2) {
      avgClass = "grailed-plus__row--alert";
    }

    panel.appendChild(createRow(doc, "Avg. Price Drop", avgText, avgClass));
    panel.appendChild(createRow(doc, "Next Expected Drop", buildExpectedDropText(listing, metrics)));
    panel.appendChild(
      createRow(doc, "Seller Account Created", formatDate(listing.seller && listing.seller.createdAt))
    );

    var actions = doc.createElement("div");
    actions.className = "grailed-plus__actions";

    var metadataButton = doc.createElement("button");
    metadataButton.type = "button";
    metadataButton.className = "grailed-plus__button";
    metadataButton.textContent = "Listing Metadata";
    if (typeof metadataButton.addEventListener === "function") {
      metadataButton.addEventListener("click", function () {
        openMetadataInNewTab(rawListing, listing);
      });
    } else {
      metadataButton.onclick = function () {
        openMetadataInNewTab(rawListing, listing);
      };
    }

    actions.appendChild(metadataButton);
    panel.appendChild(actions);

    if (mountNode.parentNode) {
      if (typeof mountNode.insertAdjacentElement === "function") {
        mountNode.insertAdjacentElement("afterend", panel);
      } else if (mountNode.nextSibling) {
        mountNode.parentNode.insertBefore(panel, mountNode.nextSibling);
      } else {
        mountNode.parentNode.appendChild(panel);
      }
    } else if (doc.body) {
      doc.body.appendChild(panel);
    }

    return panel;
  }

  return {
    PANEL_ATTR: PANEL_ATTR,
    PANEL_ATTR_VALUE: PANEL_ATTR_VALUE,
    findMountNode: findMountNode,
    removeExistingPanels: removeExistingPanels,
    renderPanel: renderPanel,
    formatCurrency: formatCurrency
  };
});

(function () {
  "use strict";

  if (globalThis.__grailedPlusBooted) {
    return;
  }
  globalThis.__grailedPlusBooted = true;

  var Url = globalThis.GrailedPlusUrl;
  var Extract = globalThis.GrailedPlusExtractListing;
  var Metrics = globalThis.GrailedPlusMetrics;
  var Render = globalThis.GrailedPlusRender;

  if (!Url || !Extract || !Metrics || !Render) {
    console.error("[Grailed+] Failed to initialize: missing modules");
    return;
  }

  var MAX_RETRIES = 12;
  var RETRY_DELAY_MS = 500;
  var MAX_RETRY_WINDOW_MS = 15000;
  var URL_POLL_INTERVAL_MS = 1000;

  var state = {
    lastUrl: String(location.href),
    retryTimer: null,
    urlPollTimer: null,
    retryStartedAtMs: null,
    mutationObserver: null
  };

  function isDebugEnabled() {
    var enabled = false;

    if (globalThis && globalThis.GRAILED_PLUS_DEBUG === true) {
      return true;
    }

    try {
      enabled = localStorage.getItem("grailed-plus:debug") === "1";
    } catch (_) {
      enabled = false;
    }

    if (enabled) {
      return true;
    }

    try {
      var params = new URLSearchParams(globalThis.location.search || "");
      return params.get("gp_debug") === "1";
    } catch (_) {
      return false;
    }
  }

  function log() {
    if (!isDebugEnabled()) {
      return;
    }
    var args = Array.prototype.slice.call(arguments);
    args.unshift("[Grailed+]");
    console.debug.apply(console, args);
  }

  function clearRetryTimer(resetWindow) {
    if (state.retryTimer) {
      clearTimeout(state.retryTimer);
      state.retryTimer = null;
    }
    if (resetWindow) {
      state.retryStartedAtMs = null;
    }
  }

  function shouldStopRetryWindow() {
    if (state.retryStartedAtMs == null) {
      state.retryStartedAtMs = Date.now();
      return false;
    }

    return Date.now() - state.retryStartedAtMs > MAX_RETRY_WINDOW_MS;
  }

  function scheduleHydrationObserver() {
    if (typeof MutationObserver !== "function") {
      return;
    }
    if (state.mutationObserver) {
      return;
    }

    var obs = new MutationObserver(function () {
      if (!Url.isListingPath(location.pathname)) {
        return;
      }

      var nextDataNode = document.getElementById("__NEXT_DATA__");
      if (nextDataNode && nextDataNode.textContent) {
        log("hydration observer detected next data");
        refresh("mutation_observer");
      }
    });

    obs.observe(document.documentElement || document.body, {
      childList: true,
      subtree: true
    });

    state.mutationObserver = obs;
  }

  function disconnectHydrationObserver() {
    if (state.mutationObserver && typeof state.mutationObserver.disconnect === "function") {
      state.mutationObserver.disconnect();
    }
    state.mutationObserver = null;
  }

  function renderUnavailable(statusMessage) {
    if (!Url.isListingPath(location.pathname)) {
      return;
    }

    var mountNode = Render.findMountNode(document);
    if (!mountNode) {
      return;
    }

    Render.renderPanel({
      listing: {
        id: "unknown",
        title: "",
        priceDrops: [],
        createdAt: null,
        priceUpdatedAt: null,
        seller: {
          createdAt: null
        },
        rawListing: null
      },
      metrics: {
        avgDropAmount: null,
        avgDropPercent: null,
        expectedDropDays: null,
        expectedDropState: "insufficient_data"
      },
      mountNode: mountNode,
      rawListing: null,
      statusMessage: statusMessage
    });
  }

  function scheduleRetry(reason, attempt) {
    if (attempt >= MAX_RETRIES || shouldStopRetryWindow()) {
      log("retry limit reached", {
        reason: reason,
        attempt: attempt
      });
      disconnectHydrationObserver();
      renderUnavailable("Feature unavailable: unable to read listing data.");
      return;
    }

    scheduleHydrationObserver();

    clearRetryTimer(false);
    state.retryTimer = setTimeout(function () {
      run("retry:" + reason, attempt + 1);
    }, RETRY_DELAY_MS);

    log("scheduled retry", {
      reason: reason,
      attempt: attempt
    });
  }

  function run(reason, attempt) {
    if (!Url.isListingPath(location.pathname)) {
      clearRetryTimer(true);
      disconnectHydrationObserver();
      Render.removeExistingPanels(document);
      return;
    }

    var nextData = Extract.readNextDataFromDocument(document);
    if (!nextData) {
      scheduleRetry("missing_next_data", attempt);
      return;
    }

    var listing = Extract.extractListing(nextData);
    if (!listing || !listing.id) {
      scheduleRetry("missing_listing", attempt);
      return;
    }

    var mountNode = Render.findMountNode(document);
    if (!mountNode) {
      scheduleRetry("missing_mount", attempt);
      return;
    }

    var metrics = Metrics.computeMetrics(listing);
    Render.renderPanel({
      listing: listing,
      metrics: metrics,
      mountNode: mountNode,
      rawListing: listing.rawListing
    });

    disconnectHydrationObserver();
    state.retryStartedAtMs = null;

    log("rendered", {
      reason: reason,
      attempt: attempt,
      listingId: listing.id
    });
  }

  function refresh(reason) {
    clearRetryTimer(true);
    run(reason, 0);
  }

  function onNavigation(reason) {
    if (location.href === state.lastUrl && reason !== "initial") {
      return;
    }

    state.lastUrl = String(location.href);
    refresh(reason);
  }

  function patchHistoryMethod(methodName) {
    var original = history[methodName];
    if (typeof original !== "function") {
      return;
    }

    history[methodName] = function () {
      var result = original.apply(this, arguments);
      window.dispatchEvent(new Event("grailed-plus:navigation"));
      return result;
    };
  }

  function setupNavigationListeners() {
    patchHistoryMethod("pushState");
    patchHistoryMethod("replaceState");

    window.addEventListener("grailed-plus:navigation", function () {
      onNavigation("history");
    });

    window.addEventListener("popstate", function () {
      onNavigation("popstate");
    });

    state.urlPollTimer = setInterval(function () {
      if (location.href !== state.lastUrl) {
        onNavigation("url_poll");
      }
    }, URL_POLL_INTERVAL_MS);
  }

  setupNavigationListeners();

  if (document.readyState === "loading") {
    document.addEventListener(
      "DOMContentLoaded",
      function () {
        onNavigation("dom_content_loaded");
      },
      { once: true }
    );
  }

  onNavigation("initial");
})();
